version: "3.7"
services:
  archelon-stomp-listener:
    image: docker.lib.umd.edu/archelon
    env_file:
      - docker-archelon.env
    command: [ "bundle", "exec", "rails", "stomp:listen" ]
  archelon:
    image: docker.lib.umd.edu/archelon
    ports:
      - 3000:3000
    env_file:
      - docker-archelon.env
    volumes:
      - archelon-import-export-data:/var/opt/archelon:ro
  archelon-sftp:
    image: docker.lib.umd.edu/archelon-sftp:latest
    ports:
      - 2200:22
    volumes:
      - archelon-import-export-data:/data
  archelon-db:
    image: postgres:9.5.16
    environment:
      POSTGRES_USER: archelon
      POSTGRES_PASSWORD: archelon
      POSTGRES_DB: archelon
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  archelon-import-export-data:
  dbdata:
networks:
  default:
    external: true
    name: umd-fcrepo_default
