default: &default
  # where to find the zip files of completed export jobs
  dir: <%= ENV['EXPORT_DIR'].present? ? ENV['EXPORT_DIR'] : Rails.root.join('exports') %>
  # the base location to use to generate the output-dest parameter for plastron
  # this can either be a local file path, or an SFTP URI to a remote server
  base_destination: <%= ENV['EXPORT_BASE_DESTINATION'].present? ? ENV['EXPORT_BASE_DESTINATION'] : Rails.root.join('exports') %>

development:
  <<: *default

test:
  dir: <%= Rails.root.join('test', 'exports') %>
  base_destination: <%= Rails.root.join('test', 'exports') %>

production:
  dir: <%= ENV['EXPORT_DIR'] %>
  # this should be something like sftp://plastron@archelon.lib.umd.edu/exports
  base_destination: <%= ENV['EXPORT_BASE_DESTINATION'] %>
