# config/ldap.yml
# LDAP server and grouper groups configuration settings
default: &default
  host: <%= ENV['LDAP_HOST'] %>
  port: <%= ENV['LDAP_PORT'] %>
  bind_dn: <%= ENV['LDAP_BIND_DN'] %>
  bind_password: <%= ENV['LDAP_BIND_PASSWORD'] %>
  base: ou=people,dc=umd,dc=edu
  name_attr: umdisplayname
  groups_attr: ibm-allgroups
  grouper_admin_group: cn=Application_Roles:Libraries:Archelon:Archelon-Administrator,ou=grouper,ou=group,dc=umd,dc=edu
  grouper_user_group: cn=Application_Roles:Libraries:Archelon:Archelon-User,ou=grouper,ou=group,dc=umd,dc=edu

development:
  <<: *default

vagrant:
  <<: *default

test:
  <<: *default

production:
  <<: *default