http://hdl.handle.net/1903.1/: ArchivesSpace
https://id.loc.gov/authorities/names/: LCNAF
https://id.loc.gov/authorities/genreForms/: LCGFT
https://id.loc.gov/authorities/subjects/: LCSH
http://vocab.getty.edu/page/aat/: AAT
http://vocab.getty.edu/aat/: AAT
http://sws.geonames.org/: GeoNames
http://viaf.org/viaf/: VIAF
http://id.loc.gov/vocabulary/graphicMaterials/: TGM
