default: &default
  host: <%= ENV['STOMP_HOST'] %>
  port: <%= ENV['STOMP_PORT'] %>
  destinations:
    jobs: /queue/plastron.jobs
    job_status: /topic/plastron.jobs.status
    jobs_completed: /queue/plastron.jobs.completed

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
